MENU = {

    "Veg": {

        "Biryani": [
            {"name": "Vegetable Biryani", "price": 120},
            {"name": "Paneer Biryani", "price": 150},
            {"name": "Mushroom Biryani", "price": 140},
            {"name": "Corn Biryani", "price": 130},
            {"name": "Soya Chunk Biryani", "price": 120},
            {"name": "Cauliflower Biryani", "price": 130},
            {"name": "Palak (Spinach) Biryani", "price": 110},
            {"name": "Brinjal Biryani", "price": 110},
            {"name": "Kaju Biryani", "price": 160},
            {"name": "Mixed Vegetable Biryani", "price": 140},
            {"name": "Paneer Tikka Biryani", "price": 170},
            {"name": "Malai Paneer Biryani", "price": 160},
            {"name": "Methi Biryani", "price": 130},
            {"name": "Mint Biryani", "price": 120},
            {"name": "Green Peas Biryani", "price": 130},
            {"name": "Broccoli Biryani", "price": 150},
            {"name": "Beetroot Biryani", "price": 120},
            {"name": "Tomato Biryani", "price": 110},
            {"name": "Capsicum Biryani", "price": 130},
            {"name": "Veg Dum Biryani", "price": 150},
            {"name": "Hyderabadi Veg Biryani", "price": 160},
            {"name": "Andhra Veg Biryani", "price": 140},
            {"name": "Mushroom Pepper Biryani", "price": 150},
            {"name": "Paneer Masala Biryani", "price": 160},
            {"name": "Cheese Biryani", "price": 170},
            {"name": "Tandoori Paneer Biryani", "price": 180},
            {"name": "Veg Handi Biryani", "price": 150},
            {"name": "Veg Special Biryani", "price": 180},
            {"name": "Royal Veg Biryani", "price": 190},
            {"name": "Cashew Paneer Biryani", "price": 180},
            {"name": "Corn Paneer Biryani", "price": 160},
            {"name": "Spinach Paneer Biryani", "price": 160},
            {"name": "Mushroom Paneer Biryani", "price": 170},
            {"name": "Soya Paneer Biryani", "price": 160},
            {"name": "Vegetable Kebab Biryani", "price": 170},
            {"name": "Veg Kofta Biryani", "price": 160},
            {"name": "Paneer Kofta Biryani", "price": 180},
            {"name": "Kashmiri Veg Biryani", "price": 170},
            {"name": "Lucknowi Veg Biryani", "price": 160},
            {"name": "Royal Kaju Veg Biryani", "price": 200}
        ],

        "Fried Rice": [
            {"name": "Vegetable Fried Rice", "price": 110},
            {"name": "Paneer Fried Rice", "price": 140},
            {"name": "Mushroom Fried Rice", "price": 130},
            {"name": "Corn Fried Rice", "price": 120},
            {"name": "Schezwan Fried Rice", "price": 130},
            {"name": "Garlic Fried Rice", "price": 120},
            {"name": "Manchurian Fried Rice", "price": 140},
            {"name": "Cashew Fried Rice", "price": 150},
            {"name": "Chilli Garlic Fried Rice", "price": 130},
            {"name": "Paneer Schezwan Fried Rice", "price": 150},
            {"name": "Mushroom Schezwan Fried Rice", "price": 145},
            {"name": "Corn Schezwan Fried Rice", "price": 140},
            {"name": "Triple Schezwan Fried Rice", "price": 160},
            {"name": "Veg Hong Kong Fried Rice", "price": 150},
            {"name": "Veg Shanghai Fried Rice", "price": 150},
            {"name": "Veg Singapore Fried Rice", "price": 150},
            {"name": "Veg Thai Fried Rice", "price": 160},
            {"name": "Basil Veg Fried Rice", "price": 150},
            {"name": "Pepper Veg Fried Rice", "price": 130},
            {"name": "Chilli Paneer Fried Rice", "price": 150},
            {"name": "Gobi Fried Rice", "price": 130},
            {"name": "Soya Fried Rice", "price": 130},
            {"name": "Spinach Fried Rice", "price": 125},
            {"name": "Broccoli Fried Rice", "price": 150},
            {"name": "Beetroot Fried Rice", "price": 120},
            {"name": "Capsicum Fried Rice", "price": 125},
            {"name": "Mixed Veg Fried Rice", "price": 140},
            {"name": "Veg Manchow Fried Rice", "price": 145},
            {"name": "Paneer Chilli Fried Rice", "price": 155},
            {"name": "Mushroom Garlic Fried Rice", "price": 140},
            {"name": "Veg Hot Garlic Fried Rice", "price": 145},
            {"name": "Veg Burnt Garlic Fried Rice", "price": 150},
            {"name": "Veg Double Eggless Fried Rice", "price": 140},
            {"name": "Kaju Fried Rice", "price": 160},
            {"name": "Cheese Fried Rice", "price": 160},
            {"name": "Tandoori Paneer Fried Rice", "price": 170},
            {"name": "Veg Special Fried Rice", "price": 170},
            {"name": "Royal Veg Fried Rice", "price": 180},
            {"name": "Chef Special Veg Fried Rice", "price": 180},
            {"name": "Dragon Veg Fried Rice", "price": 160}
        ],

        "Starters": [
            {"name": "Gobi 65", "price": 100},
            {"name": "Paneer 65", "price": 140},
            {"name": "Gobi Manchurian", "price": 120},
            {"name": "Paneer Manchurian", "price": 150},
            {"name": "Mushroom 65", "price": 130},
            {"name": "Chilli Paneer", "price": 150},
            {"name": "Chilli Mushroom", "price": 140},
            {"name": "Baby Corn Manchurian", "price": 130},
            {"name": "Crispy Corn", "price": 120},
            {"name": "French Fries", "price": 100},
            {"name": "Vegetable Spring Roll", "price": 120},
            {"name": "Paneer Tikka", "price": 160},
            {"name": "Mushroom Tikka", "price": 150},
            {"name": "Crispy Gobi", "price": 110},
            {"name": "Veg Cutlet", "price": 90},
            {"name": "Baby Corn 65", "price": 120},
            {"name": "Crispy Baby Corn", "price": 130},
            {"name": "Paneer Pepper Fry", "price": 150},
            {"name": "Paneer Chilli Dry", "price": 150},
            {"name": "Mushroom Pepper Fry", "price": 140},
            {"name": "Mushroom Chilli Dry", "price": 140},
            {"name": "Gobi Chilli Dry", "price": 120},
            {"name": "Veg Seekh Kebab", "price": 150},
            {"name": "Hara Bhara Kebab", "price": 140},
            {"name": "Paneer Malai Tikka", "price": 180},
            {"name": "Achari Paneer Tikka", "price": 170},
            {"name": "Tandoori Paneer", "price": 180},
            {"name": "Tandoori Mushroom", "price": 170},
            {"name": "Veg Cheese Balls", "price": 150},
            {"name": "Cheese Corn Balls", "price": 160},
            {"name": "Crispy Vegetable", "price": 130},
            {"name": "Veg Salt Pepper", "price": 130},
            {"name": "Veg Dragon", "price": 150},
            {"name": "Veg 555", "price": 140},
            {"name": "Veg Lollipop", "price": 150},
            {"name": "Corn Tikki", "price": 120},
            {"name": "Aloo Tikki", "price": 90},
            {"name": "Masala Fries", "price": 120},
            {"name": "Peri Peri Fries", "price": 130},
            {"name": "Cheese Fries", "price": 150}
        ]
    },

    "Non-Veg": {

        "Biryani": [
            {"name": "Chicken Biryani", "price": 180},
            {"name": "Chicken 65 Biryani", "price": 200},
            {"name": "Mutton Biryani", "price": 250},
            {"name": "Egg Biryani", "price": 140},
            {"name": "Fish Biryani", "price": 220},
            {"name": "Prawn Biryani", "price": 240},
            {"name": "Chicken Tikka Biryani", "price": 220},
            {"name": "Chicken Lollipop Biryani", "price": 230},
            {"name": "Pepper Chicken Biryani", "price": 210},
            {"name": "Andhra Chicken Biryani", "price": 200},
            {"name": "Ambur Chicken Biryani", "price": 190},
            {"name": "Hyderabadi Chicken Biryani", "price": 220},
            {"name": "Chicken Dum Biryani", "price": 210},
            {"name": "Chicken Handi Biryani", "price": 220},
            {"name": "Chicken Special Biryani", "price": 240},
            {"name": "Chicken Mughlai Biryani", "price": 230},
            {"name": "Chicken Kebab Biryani", "price": 230},
            {"name": "Chicken 555 Biryani", "price": 220},
            {"name": "Chilli Chicken Biryani", "price": 220},
            {"name": "Garlic Chicken Biryani", "price": 220},
            {"name": "Mutton Dum Biryani", "price": 270},
            {"name": "Mutton Special Biryani", "price": 290},
            {"name": "Mutton Pepper Biryani", "price": 280},
            {"name": "Mutton Fry Biryani", "price": 280},
            {"name": "Fish Tikka Biryani", "price": 240},
            {"name": "Fish Fry Biryani", "price": 250},
            {"name": "Prawn Masala Biryani", "price": 260},
            {"name": "Prawn Special Biryani", "price": 280},
            {"name": "Egg Chicken Biryani", "price": 210},
            {"name": "Double Egg Chicken Biryani", "price": 220},
            {"name": "Chicken Keema Biryani", "price": 230},
            {"name": "Chicken Seekh Kebab Biryani", "price": 240},
            {"name": "Chicken Malai Biryani", "price": 230},
            {"name": "Chicken Schezwan Biryani", "price": 230},
            {"name": "Chicken Pepper Fry Biryani", "price": 230},
            {"name": "Chicken Chilli Biryani", "price": 230},
            {"name": "Chicken Dragon Biryani", "price": 240},
            {"name": "Royal Chicken Biryani", "price": 260},
            {"name": "Royal Mutton Biryani", "price": 300},
            {"name": "Chef Special Non-Veg Biryani", "price": 300}
        ],

        "Fried Rice": [
            {"name": "Chicken Fried Rice", "price": 160},
            {"name": "Chicken Schezwan Fried Rice", "price": 180},
            {"name": "Chicken 65 Fried Rice", "price": 190},
            {"name": "Egg Fried Rice", "price": 130},
            {"name": "Egg Schezwan Fried Rice", "price": 150},
            {"name": "Chicken Manchurian Fried Rice", "price": 180},
            {"name": "Chicken Garlic Fried Rice", "price": 170},
            {"name": "Chicken Pepper Fried Rice", "price": 170},
            {"name": "Chicken Chilli Fried Rice", "price": 180},
            {"name": "Mixed Non-Veg Fried Rice", "price": 220},
            {"name": "Prawn Fried Rice", "price": 200},
            {"name": "Fish Fried Rice", "price": 190},
            {"name": "Chicken Hong Kong Fried Rice", "price": 190},
            {"name": "Chicken Shanghai Fried Rice", "price": 190},
            {"name": "Chicken Singapore Fried Rice", "price": 190},
            {"name": "Chicken Thai Fried Rice", "price": 200},
            {"name": "Chicken Hot Garlic Fried Rice", "price": 190},
            {"name": "Chicken Burnt Garlic Fried Rice", "price": 200},
            {"name": "Chicken Dragon Fried Rice", "price": 200},
            {"name": "Chicken 555 Fried Rice", "price": 190},
            {"name": "Chicken Majestic Fried Rice", "price": 200},
            {"name": "Chicken Lollipop Fried Rice", "price": 210},
            {"name": "Chicken Tikka Fried Rice", "price": 210},
            {"name": "Chicken Kebab Fried Rice", "price": 200},
            {"name": "Egg Chicken Fried Rice", "price": 180},
            {"name": "Double Egg Chicken Fried Rice", "price": 190},
            {"name": "Chicken Egg Schezwan Fried Rice", "price": 200},
            {"name": "Prawn Schezwan Fried Rice", "price": 220},
            {"name": "Prawn Garlic Fried Rice", "price": 210},
            {"name": "Fish Schezwan Fried Rice", "price": 210},
            {"name": "Fish Garlic Fried Rice", "price": 200},
            {"name": "Mutton Fried Rice", "price": 220},
            {"name": "Mutton Schezwan Fried Rice", "price": 240},
            {"name": "Mutton Pepper Fried Rice", "price": 230},
            {"name": "Chicken Triple Schezwan Fried Rice", "price": 220},
            {"name": "Chicken Special Fried Rice", "price": 220},
            {"name": "Royal Chicken Fried Rice", "price": 240},
            {"name": "Royal Prawn Fried Rice", "price": 250},
            {"name": "Royal Mixed Fried Rice", "price": 260},
            {"name": "Chef Special Non-Veg Fried Rice", "price": 260}
        ],

        "Starters": [
            {"name": "Chicken 65", "price": 160},
            {"name": "Chicken 555", "price": 170},
            {"name": "Chilli Chicken", "price": 170},
            {"name": "Chicken Manchurian", "price": 180},
            {"name": "Chicken Lollipop", "price": 200},
            {"name": "Chicken Wings", "price": 190},
            {"name": "Chicken Tikka", "price": 200},
            {"name": "Chicken Kebab", "price": 180},
            {"name": "Pepper Chicken", "price": 170},
            {"name": "Garlic Chicken", "price": 180},
            {"name": "Chicken Majestic", "price": 200},
            {"name": "Chicken Dragon", "price": 190},
            {"name": "Chicken Pakora", "price": 160},
            {"name": "Chicken Spring Roll", "price": 170},
            {"name": "Fish Finger", "price": 200},
            {"name": "Fish 65", "price": 190},
            {"name": "Chilli Fish", "price": 200},
            {"name": "Prawn 65", "price": 220},
            {"name": "Chilli Prawn", "price": 230},
            {"name": "Mutton Pepper Fry", "price": 250},
            {"name": "Chicken Pepper Fry", "price": 180},
            {"name": "Chicken Chilli Dry", "price": 180},
            {"name": "Chicken Salt Pepper", "price": 180},
            {"name": "Chicken Hot Garlic", "price": 190},
            {"name": "Chicken Schezwan", "price": 190},
            {"name": "Chicken Manchow", "price": 180},
            {"name": "Chicken Drumsticks", "price": 210},
            {"name": "Chicken Seekh Kebab", "price": 220},
            {"name": "Chicken Malai Tikka", "price": 230},
            {"name": "Chicken Achari Tikka", "price": 220},
            {"name": "Tandoori Chicken", "price": 240},
            {"name": "Tandoori Chicken Half", "price": 280},
            {"name": "Tandoori Chicken Full", "price": 500},
            {"name": "Chicken Reshmi Kebab", "price": 230},
            {"name": "Chicken Tangdi Kebab", "price": 240},
            {"name": "Chicken Hariyali Kebab", "price": 230},
            {"name": "Fish Tikka", "price": 230},
            {"name": "Fish Fry", "price": 220},
            {"name": "Prawn Fry", "price": 240},
            {"name": "Prawn Pepper Fry", "price": 250}
        ]
    },

    "Drinks": {

        "Drinks": [
            {"name": "Coca Cola", "price": 50},
            {"name": "Pepsi", "price": 50},
            {"name": "Sprite", "price": 50},
            {"name": "Fanta", "price": 50},
            {"name": "7 Up", "price": 50},
            {"name": "Mountain Dew", "price": 50},
            {"name": "Limca", "price": 50},
            {"name": "Fresh Lime Soda", "price": 60},
            {"name": "Fresh Lime Juice", "price": 70},
            {"name": "Orange Juice", "price": 80},
            {"name": "Mango Juice", "price": 80},
            {"name": "Tea", "price": 30},
            {"name": "Coffee", "price": 40},
            {"name": "Cold Coffee", "price": 90},
            {"name": "Milkshake", "price": 100},
            {"name": "Strawberry Milkshake", "price": 110},
            {"name": "Chocolate Milkshake", "price": 110},
            {"name": "Vanilla Milkshake", "price": 100},
            {"name": "Mango Milkshake", "price": 110},
            {"name": "Banana Milkshake", "price": 100},
            {"name": "Oreo Milkshake", "price": 130},
            {"name": "KitKat Milkshake", "price": 140},
            {"name": "Cold Chocolate", "price": 110},
            {"name": "Lemon Tea", "price": 40},
            {"name": "Ginger Tea", "price": 40},
            {"name": "Masala Tea", "price": 50},
            {"name": "Green Tea", "price": 50},
            {"name": "Black Tea", "price": 40},
            {"name": "Filter Coffee", "price": 50},
            {"name": "Cappuccino", "price": 100},
            {"name": "Latte", "price": 110},
            {"name": "Espresso", "price": 80},
            {"name": "Americano", "price": 90},
            {"name": "Iced Tea", "price": 80},
            {"name": "Peach Iced Tea", "price": 90},
            {"name": "Lemon Iced Tea", "price": 80},
            {"name": "Virgin Mojito", "price": 120},
            {"name": "Blue Lagoon", "price": 120},
            {"name": "Mint Cooler", "price": 100},
            {"name": "Fruit Punch", "price": 130}
        ]
    },

    "Desserts": {

        "Desserts": [
            {"name": "Vanilla Ice Cream", "price": 60},
            {"name": "Chocolate Ice Cream", "price": 70},
            {"name": "Strawberry Ice Cream", "price": 70},
            {"name": "Butterscotch Ice Cream", "price": 80},
            {"name": "Black Currant Ice Cream", "price": 80},
            {"name": "Chocolate Sundae", "price": 100},
            {"name": "Brownie with Ice Cream", "price": 120},
            {"name": "Gulab Jamun", "price": 60},
            {"name": "Rasmalai", "price": 80},
            {"name": "Gajar Halwa", "price": 70},
            {"name": "Kulfi", "price": 70},
            {"name": "Chocolate Cake", "price": 100},
            {"name": "Black Forest Cake", "price": 120},
            {"name": "Caramel Pudding", "price": 90},
            {"name": "Fruit Salad with Ice Cream", "price": 110},
            {"name": "Vanilla Sundae", "price": 90},
            {"name": "Strawberry Sundae", "price": 100},
            {"name": "Butterscotch Sundae", "price": 110},
            {"name": "Brownie", "price": 90},
            {"name": "Chocolate Brownie", "price": 100},
            {"name": "Chocolate Lava Cake", "price": 130},
            {"name": "Red Velvet Cake", "price": 130},
            {"name": "Pineapple Cake", "price": 110},
            {"name": "White Forest Cake", "price": 130},
            {"name": "Cheesecake", "price": 140},
            {"name": "Blueberry Cheesecake", "price": 150},
            {"name": "Chocolate Cheesecake", "price": 150},
            {"name": "Carrot Cake", "price": 110},
            {"name": "Mango Cake", "price": 120},
            {"name": "Strawberry Cake", "price": 120},
            {"name": "Kesar Kulfi", "price": 90},
            {"name": "Malai Kulfi", "price": 90},
            {"name": "Pista Kulfi", "price": 100},
            {"name": "Mango Kulfi", "price": 90},
            {"name": "Jalebi", "price": 60},
            {"name": "Rasgulla", "price": 70},
            {"name": "Kheer", "price": 70},
            {"name": "Payasam", "price": 70},
            {"name": "Fruit Custard", "price": 90},
            {"name": "Falooda", "price": 130}
        ]
    }
}